name: PlayerWarpsReborn
version: '1.4'
main: net.devscape.playerwarpsreborn.PlayerWarpsReborn
api-version: '1.13'
depend:
  - NBTAPI
softdepend:
  - Vault
  - PlaceholderAPI

commands:
  playerwarpsreborn:
    aliases: [pwr, pw, playerwarps, pwarps, pwarp]